version: "3.9"
networks:
  myAppNetwork:
    driver: bridge

services:
#   postgresServerDb:
#     container_name: container-postgres
#     image: postgres:17.9-bookworm
#     ports:
#       - "5432:5432"
#     env_file:
#       - .env
#     environment:
#       - POSTGRES_USER=${POSTGRES_USER}
#       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#       - POSTGRES_DB=${POSTGRES_DB}
#     networks:
#       - myAppNetwork
#     volumes:
# #       - d:/web/pd322/postgresql:/var/lib/postgresql/data  # Use the volume name msvol here
#         - /data/postgresql/data:/var/lib/postgresql/data
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
#       interval: 10s
#       timeout: 5s
#       retries: 5
#       start_period: 30s
#     deploy:
#       restart_policy:
#         condition: on-failure
#         max_attempts: 5

  
  client:
    container_name: olx_client_container
    image: macnaer/frontend
    restart: on-failure
    ports:
      - "80:80"